name: fwi-marmousi-deepwave-gpu
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - matplotlib
  - scikit-image
  - jupyterlab
  - ipykernel
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - pip:
      - deepwave
